### ISSUE TITLE
Minimal example won't run

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/sldp#2]
Hi,

The [minimal example](https://github.com/yakirr/sldp/wiki/Minimal-example) for the package won't run since the dataset isn't found when running:

```
-bash-4.2$ wget https://data.broadinstitute.org/alkesgroup/SLDP/annots/SydhK562Irf1Ifng6h.tar
```

See below:
```
--2021-09-10 13:01:55--  https://data.broadinstitute.org/alkesgroup/SLDP/annots/SydhK562Irf1Ifng6h.tar
Resolving data.broadinstitute.org (data.broadinstitute.org)... 69.173.92.29
Connecting to data.broadinstitute.org (data.broadinstitute.org)|69.173.92.29|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://alkesgroup.broadinstitute.org/SLDP/annots/SydhK562Irf1Ifng6h.tar [following]
--2021-09-10 13:01:55--  https://alkesgroup.broadinstitute.org/SLDP/annots/SydhK562Irf1Ifng6h.tar
Resolving alkesgroup.broadinstitute.org (alkesgroup.broadinstitute.org)... 34.120.167.96
Connecting to alkesgroup.broadinstitute.org (alkesgroup.broadinstitute.org)|34.120.167.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-10 13:01:56 ERROR 404: Not Found.
```

I'm trying to run this to understand the format of the signed function annotation files but maybe you can answer my question here instead. I know they need to be named i.sannot.gz where i is the chromosome number and also they must contain:

```
SNP        A1      A2      annotname
rs7526076  A       G       0.3
rs4075116  T       C       0
rs3934834  T       C       -0.9
```

but my question is, does the headers SNP, A1, A2 annotname need to be included? I'm getting a strange error when running SLDP where the functions gets to the 
```
reading annot ./.../annots/
```
then  it fails with the error:
```
KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'
```

**Comment by yakirr** [comment]
Alan,

Thanks for drawing this our attention -- we've fixed the broken URLs; let us know if the example works now.

For the error that you're getting: do you mind including the command that produces the error and then the full output that results when you run it?

**Comment by Al-Murphy** [comment]
Great thanks! However just a few notes on this:

SydhK562Irf1Ifng6h when you run tar to unzip doesn't create a folder but instead puts the files in the working directory so I had to update the call to sldp to be the following to get it to work:

```
sldp --pss-chr CD.KG3.95/ --sannot-chr ./ --outfile-stem CD.Irf1 --config sldp.config.json
```

It also appears the reference panel links are still incorrect in the minimal example. They are missing the subfolder `refpanel`, for example, the LD blocks reference panel link, it should be pointing towards:

https://data.broadinstitute.org/alkesgroup/SLDP/refpanel/pickrell_ldblocks.hg19.eur.bed

Also, I think these downloads for the reference panel should be included in the minimal example as I couldn't get it to run without them:

```
wget https://data.broadinstitute.org/alkesgroup/SLDP/refpanel/1000G_hm3_noMHC.rsid
```

and 

```
wget https://data.broadinstitute.org/alkesgroup/SLDP/refpanel/KG3.tar.gz &&
tar -xzf KG3.tar.gz &&
rm KG3.tar.gz
```

Ignore my runtime issue for now, I can repost with a separate issue if it continues, it could have been related to the reference genome.

**Comment by yakirr** [comment]
Alan,

Thank you for this helpful information! We've updated the paths in the MWE.
